name: deploy
on:
  push:
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - id: 'auth'
      uses: 'google-github-actions/auth@v0'
      with:
        credentials_json: '${{ secrets.gcp_credentials }}'
    - uses: actions/setup-python@v2
      with:
        python-version: 3.9.12
    - uses: snok/install-poetry@v1
    - id: 'install'
      run: poetry install --no-interaction --no-root
    - id: 'mypy'
      run: poetry run mypy .
    - id: 'test'
      run: poetry run pytest
    - id: 'dry-mlb'
      run: DRY_RUN=True poetry run python mlb_dryrun.py
    - id: 'dry-nhl'
      run: DRY_RUN=True poetry run python nhl_dryrun.py
    # - id: 'dry-nba'
    #  run: DRY_RUN=True poetry run python nba_dryrun.py
    - id: 'dry-nfl'
      run: DRY_RUN=True poetry run python nfl_dryrun.py

  deploy:
    runs-on: ubuntu-latest
    needs: test
    if: github.ref == 'refs/heads/main'
    permissions:
      contents: 'read'
      id-token: 'write'

    steps:
    - uses: actions/checkout@v3

    - id: 'auth'
      uses: 'google-github-actions/auth@v0'
      with:
        credentials_json: '${{ secrets.gcp_credentials }}'

    - id: 'deploy'
      uses: 'google-github-actions/deploy-cloud-functions@v0'
      with:
        name: 'projects/greg-finley/locations/us-central1/functions/mlb-alphabet-game'
        runtime: 'python310'
        entry_point: 'run'
        memory_mb: 512
        secret_environment_variables: 'MLB_TWITTER_ACCESS_SECRET=projects/greg-finley/secrets/MLB_TWITTER_ACCESS_SECRET/versions/latest,MLB_TWITTER_ACCESS_TOKEN=projects/greg-finley/secrets/MLB_TWITTER_ACCESS_TOKEN/versions/latest, MLB_TWITTER_CONSUMER_KEY=projects/greg-finley/secrets/MLB_TWITTER_CONSUMER_KEY/versions/latest, MLB_TWITTER_CONSUMER_SECRET=projects/greg-finley/secrets/MLB_TWITTER_CONSUMER_SECRET/versions/latest, NHL_TWITTER_ACCESS_SECRET=projects/greg-finley/secrets/NHL_TWITTER_ACCESS_SECRET/versions/latest,NHL_TWITTER_ACCESS_TOKEN=projects/greg-finley/secrets/NHL_TWITTER_ACCESS_TOKEN/versions/latest, NHL_TWITTER_CONSUMER_KEY=projects/greg-finley/secrets/NHL_TWITTER_CONSUMER_KEY/versions/latest, NHL_TWITTER_CONSUMER_SECRET=projects/greg-finley/secrets/NHL_TWITTER_CONSUMER_SECRET/versions/latest, NBA_TWITTER_ACCESS_SECRET=projects/greg-finley/secrets/NBA_TWITTER_ACCESS_SECRET/versions/latest,NBA_TWITTER_ACCESS_TOKEN=projects/greg-finley/secrets/NBA_TWITTER_ACCESS_TOKEN/versions/latest, NBA_TWITTER_CONSUMER_KEY=projects/greg-finley/secrets/NBA_TWITTER_CONSUMER_KEY/versions/latest, NBA_TWITTER_CONSUMER_SECRET=projects/greg-finley/secrets/NBA_TWITTER_CONSUMER_SECRET/versions/latest, NFL_TWITTER_ACCESS_SECRET=projects/greg-finley/secrets/NFL_TWITTER_ACCESS_SECRET/versions/latest,NFL_TWITTER_ACCESS_TOKEN=projects/greg-finley/secrets/NFL_TWITTER_ACCESS_TOKEN/versions/latest, NFL_TWITTER_CONSUMER_KEY=projects/greg-finley/secrets/NFL_TWITTER_CONSUMER_KEY/versions/latest, NFL_TWITTER_CONSUMER_SECRET=projects/greg-finley/secrets/NFL_TWITTER_CONSUMER_SECRET/versions/latest'
        timeout: 120
        event_trigger_type: 'providers/cloud.pubsub/eventTypes/topic.publish'
        event_trigger_resource: 'projects/greg-finley/topics/mlb-alphabet-game'
        event_trigger_service: 'pubsub.googleapis.com'
        min_instances: 0
        max_instances: 1

